services:
  frontend:
    image: "frontend_image"
    container_name: "frontend"
    build: ./frontend
    expose: ['5000']
    ports: ["5000:5000"]
    environment:
      FLASK_ENV: "development"
  backend:
    image: "backend_image"
    container_name: "backend"
    build: ./backend
    expose: ['5001']
    ports: ["5001:5001"]
    environment:
      FLASK_ENV: "development"
  